pip install pysimplegui
pip3 install pysimplegui
pip install numpy
pip3 install numpy
pip install matplotlib
pip3 install matplotlib
pip install PIL
pip3 install PIL
pip install ipywidgets
pip3 install ipywidgets